import React, {useState, useEffect} from 'react';
import {Loader, Card, FormFiled} from '../components';

const RenderCard = ({data, title}) => {
    if(data?.length > 0) {
        return data.map((post) => <Card key={post._id} {...post}/>)
    }
    return (
        <h2 className='mt-5 font-bold text-[#6469ff] text-xl uppercase'>{title}</h2>
    )
}

const Home = () => {
    const [loading, setLoading] = useState(false);
    const [allPosts, setAllPosts] = useState(null);
    const [searchText, setSearchText] = useState('');
  return (
    <section className='max-w-7xl mx-auto '>
        <div>
            <h1 className='font-extrabold text-[#222328] text-[32px]'>The Community showcase</h1>
            <p className='mt-2 test-[#666e75] test-[16px] max-w-[500px]'>Browse throgh a collection of imaginative and visuallly stunning images generated by DALL_E AI</p>
        </div>
        <div className='mt-16 '>
            <FormFiled />
        </div>
        <div className='mt-10'>
            {loading ? (
                <div className='flex justify-center items-center'>
                  <Loader />      
                </div>
            ): (
                <>
                    {searchText && (
                        <h2 className='font-medium text-[#666e75] text-xl mb-3'>
                            Showing results for <span className='text-[#333328]'>{searchText}</span>
                        </h2>
                    )}
                    <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3'>
                        {searchText ? (
                            <RenderCard 
                                data={[]}
                                title="No search results found"
                            />
                        ): (
                            <RenderCard 
                                data={[]}
                                title="No Posts found"
                            />
                        )}
                    </div>
                </>
            )}
        </div>
    </section>
  )
}

export default Home